"""baseline existing schema

Revision ID: 0c540de54eef
Revises: 
Create Date: 2026-09-16 00:19:46.304997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('challenge_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_type', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_type', name='uq_user_challenge')
    )
    with op.batch_alter_table('challenge_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_progress_user_id'), ['user_id'], unique=False)

    op.create_table('letter_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'letter', name='uq_user_letter')
    )
    with op.batch_alter_table('letter_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_letter_progress_user_id'), ['user_id'], unique=False)

    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('prediction', sa.String(length=1), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('challenge_type', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_sessions_letter'), ['letter'], unique=False)
        batch_op.create_index('ix_practice_sessions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_practice_sessions_user_letter', ['user_id', 'letter'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('total_correct', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('game_meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('word_practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.String(length=64), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('challenge_type', sa.String(length=32), nullable=True),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('letter_results', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_practice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_practice_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_word_practice_sessions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_practice_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_word_practice_sessions_user_word', ['user_id', 'word_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_practice_sessions_word_id'), ['word_id'], unique=False)

    op.create_table('word_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('completions', sa.Integer(), nullable=False),
    sa.Column('correct_letters', sa.Integer(), nullable=False),
    sa.Column('total_letters', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('best_time_ms', sa.Integer(), nullable=True),
    sa.Column('total_time_ms', sa.Integer(), nullable=False),
    sa.Column('resume_index', sa.Integer(), nullable=False),
    sa.Column('letter_stats', sa.Text(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    with op.batch_alter_table('word_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_word_progress_user_word', ['user_id', 'word_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_progress_word_id'), ['word_id'], unique=False)

    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_xp_events_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_events_user_id'))
        batch_op.drop_index('ix_xp_events_user_created')
        batch_op.drop_index(batch_op.f('ix_xp_events_created_at'))

    op.drop_table('xp_events')
    with op.batch_alter_table('word_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_progress_word_id'))
        batch_op.drop_index('ix_word_progress_user_word')
        batch_op.drop_index(batch_op.f('ix_word_progress_user_id'))

    op.drop_table('word_progress')
    with op.batch_alter_table('word_practice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_practice_sessions_word_id'))
        batch_op.drop_index('ix_word_practice_sessions_user_word')
        batch_op.drop_index(batch_op.f('ix_word_practice_sessions_user_id'))
        batch_op.drop_index('ix_word_practice_sessions_user_created')
        batch_op.drop_index(batch_op.f('ix_word_practice_sessions_created_at'))

    op.drop_table('word_practice_sessions')
    op.drop_table('user_progress')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))

    op.drop_table('user_achievements')
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_practice_sessions_user_letter')
        batch_op.drop_index(batch_op.f('ix_practice_sessions_user_id'))
        batch_op.drop_index('ix_practice_sessions_user_created')
        batch_op.drop_index(batch_op.f('ix_practice_sessions_letter'))
        batch_op.drop_index(batch_op.f('ix_practice_sessions_created_at'))

    op.drop_table('practice_sessions')
    with op.batch_alter_table('letter_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_letter_progress_user_id'))

    op.drop_table('letter_progress')
    with op.batch_alter_table('challenge_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenge_progress_user_id'))

    op.drop_table('challenge_progress')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('achievements')
    # ### end Alembic commands ###
