"""add phase 2 native sign chatbot and catalog tables

Revision ID: 0002_new_tables
Revises: 0001_baseline
Create Date: 2026-09-16 00:25:38.719561

Adds the Phase 2 database-foundation tables. None of these are read from or
written to by any router/service yet (that wiring is deferred to later
phases) - this migration only creates empty structure. `words` is seeded
separately by migration 0003 (data-only), not here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_new_tables'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('checkpoint_path', sa.String(length=512), nullable=False),
    sa.Column('vocabulary_version', sa.String(length=32), nullable=True),
    sa.Column('num_classes', sa.Integer(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_type', 'version', name='uq_model_type_version')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_model_type'), ['model_type'], unique=False)

    op.create_table('native_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gloss', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('example_text', sa.Text(), nullable=True),
    sa.Column('dataset_available', sa.Boolean(), nullable=False),
    sa.Column('model_available', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('native_signs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_native_signs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_native_signs_gloss'), ['gloss'], unique=True)

    op.create_table('words',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spelling_enabled', sa.Boolean(), nullable=False),
    sa.Column('native_sign_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_category'), ['category'], unique=False)

    op.create_table('chatbot_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('native_sign_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('native_sign_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('best_confidence', sa.Float(), nullable=True),
    sa.Column('best_response_time', sa.Integer(), nullable=True),
    sa.Column('last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['native_sign_id'], ['native_signs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'native_sign_id', name='uq_user_native_sign')
    )
    with op.batch_alter_table('native_sign_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_native_sign_progress_native_sign_id'), ['native_sign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_native_sign_progress_user_id'), ['user_id'], unique=False)

    op.create_table('native_sign_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('native_sign_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_identifier', sa.String(length=255), nullable=False),
    sa.Column('local_path', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['native_sign_id'], ['native_signs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('native_sign_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_native_sign_references_native_sign_id'), ['native_sign_id'], unique=False)

    op.create_table('native_sign_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('native_sign_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['native_sign_id'], ['native_signs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('native_sign_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_native_sign_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_native_sign_sessions_native_sign_id'), ['native_sign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_native_sign_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('notification_preferences', sa.Text(), nullable=False),
    sa.Column('learning_preferences', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chatbot_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatbot_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_messages_created_at'), ['created_at'], unique=False)

    op.create_table('sign_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('predicted_label', sa.String(length=64), nullable=False),
    sa.Column('expected_label', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['native_sign_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sign_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sign_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sign_predictions_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_sign_predictions_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sign_predictions_predicted_label'), ['predicted_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_sign_predictions_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_sign_predictions_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sign_predictions_user_id'), ['user_id'], unique=False)

    op.create_table('chatbot_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chatbot_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_feedback_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_feedback_message_id'))

    op.drop_table('chatbot_feedback')
    with op.batch_alter_table('sign_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sign_predictions_user_id'))
        batch_op.drop_index('ix_sign_predictions_user_created')
        batch_op.drop_index(batch_op.f('ix_sign_predictions_session_id'))
        batch_op.drop_index(batch_op.f('ix_sign_predictions_predicted_label'))
        batch_op.drop_index(batch_op.f('ix_sign_predictions_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_sign_predictions_model_version'))
        batch_op.drop_index(batch_op.f('ix_sign_predictions_created_at'))

    op.drop_table('sign_predictions')
    with op.batch_alter_table('chatbot_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_chatbot_messages_conversation_id'))

    op.drop_table('chatbot_messages')
    op.drop_table('user_preferences')
    with op.batch_alter_table('native_sign_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_native_sign_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_native_sign_sessions_native_sign_id'))
        batch_op.drop_index(batch_op.f('ix_native_sign_sessions_created_at'))

    op.drop_table('native_sign_sessions')
    with op.batch_alter_table('native_sign_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_native_sign_references_native_sign_id'))

    op.drop_table('native_sign_references')
    with op.batch_alter_table('native_sign_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_native_sign_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_native_sign_progress_native_sign_id'))

    op.drop_table('native_sign_progress')
    with op.batch_alter_table('chatbot_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_conversations_user_id'))

    op.drop_table('chatbot_conversations')
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_category'))

    op.drop_table('words')
    with op.batch_alter_table('native_signs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_native_signs_gloss'))
        batch_op.drop_index(batch_op.f('ix_native_signs_category'))

    op.drop_table('native_signs')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_model_type'))

    op.drop_table('model_versions')
    # ### end Alembic commands ###
